### ISSUE TITLE
no syncing

### ISSUE THREAD

**Issue by AmA-sud** [mehdiirh/telegram-copy-bot#3]
the bot is not syncing

entities are added and accepted, sync command entered but to sync is happening after the message "Syncing dialogs...
"

**Comment by mehdiirh** [comment]
Hi, Please send the logs you see on terminal

**Comment by AmA-sud** [comment]
> Hi, Please send the logs you see on terminal

please let me know where to find the logs file, as in the screen shot below the powershell terminal doesn't have any output/log

![image](https://user-images.githubusercontent.com/35355360/153442735-53277837-3d3f-46c3-a52f-3d584f062d7c.png)

**Comment by mehdiirh** [comment]
bot will not create log file by default
please change the configuration of logging to save outputs in a log file from [here](https://github.com/mehdiirh/telegram-copy-bot/blob/main/main.py#L34-L37)

if you don't see any logs again, try to delete session files and relogin to your account, it might be telegram limits if you have so many chats

**Comment by mehdiirh** [comment]
Closed because of no more responses.
